---
title: "EDS213 Discussion Section"
author: "Rachel Swick"
format: html
---

```{r}
# Load packages
library(tidyverse)
library(janitor)
library(lubridate)
```

```{r}
# Load data
crop_calendar <- read_csv(here::here("data/All_data_with_climate.csv"))

production_all_noflag <- read_csv(here::here("data/Production_Crops_Livestock_E_All_Data/Production_Crops_Livestock_E_All_Data_NOFLAG.csv"))

production_all <- read_csv(here::here("data/Production_Crops_Livestock_E_All_Data/Production_Crops_Livestock_E_All_Data.csv"))

production_area_codes <- read_csv(here::here("data/Production_Crops_Livestock_E_All_Data/Production_Crops_Livestock_E_AreaCodes.csv"))

production_elements <- read_csv(here::here("data/Production_Crops_Livestock_E_All_Data/Production_Crops_Livestock_E_Elements.csv"))

production_flags <- read_csv(here::here("data/Production_Crops_Livestock_E_All_Data/Production_Crops_Livestock_E_Flags.csv"))

production_item_codes <- read_csv(here::here("data/Production_Crops_Livestock_E_All_Data/Production_Crops_Livestock_E_ItemCodes.csv"))
```


```{r}
crop_calendar_clean = crop_calendar %>% 
  clean_names() %>% 
  select(-c(state_code, county_code)) %>% 
  mutate(crop = case_when(
    crop == "Sweet.Potatoes" ~ "Sweet potatoes",
    TRUE ~ crop
  )) %>% 
  # filter out other and multiple
  filter(crop != "Other" & crop != "Multiple") %>% 
  select(c(data_id, location, crop, plant_start, plant_start_date, plant_end, plant_end_date, plant_median,
           plant_range, harvest_start, harvest_start_date, harvest_end, harvest_end_date, harvest_median,
           harvest_range, source, tot_days, harvested_area)) %>% 
  filter(if_all(ends_with("_date"), ~ !is.na(.))) %>% 
  # Using 2010, the year the data set was last updated, as a placeholder to allow easier graphing
  mutate(across(ends_with("_date"), ~ mdy(paste0(.x, "-2010"))))
  

print(unique(crop_calendar_clean$crop))
```

```{r}
# Select year and flag columns
flags_df <- production_all %>%
  pivot_longer(cols = starts_with("Y") & ends_with("F"), names_to = "Year", values_to = "Flag") %>% 
  mutate(Year = Year %>% 
           str_remove("F$")) %>% 
  select(c("Flag"))

# Pivot year columns to columns `Year` and `Amount`
production_df <- production_all_noflag %>% 
 pivot_longer(cols = starts_with("Y") , names_to = "Year", values_to = "Amount")

# Bind flag columns to production dataframe
production_clean <- cbind(production_df, flags_df) %>% 
  mutate(Year = Year %>% 
           str_remove("Y")) %>% 
  clean_names() %>% 
  filter(str_detect(item, str_c(unique(crop_calendar_clean$crop), collapse = "|"))) %>% 
  mutate(item = case_when(
    item == "Rapeseed or canola oil, crude" ~ "Rapeseed",
    item == "Sunflower-seed oil, crude" ~ "Sunflower",
    item == "Sunflower seed" ~ "Sunflower",
    item == "Maize (corn)" ~ "Maize",
    item == "Cotton seed" ~ "Cotton",
    item == "Cottonseed oil" ~ "Cotton",
    item == "Cotton lint, ginned" ~ "Cotton",
    item == "Pulses, Total" ~ "Pulses",
    item == "Cassava, fresh" ~ "Cassava",
    item == "Cassava leaves" ~ "Cassava",
    item == "Groundnuts, excluding shelled" ~ "Groundnuts",
    TRUE ~ item
  ))
         
print(unique(production_clean$item))

```

```{r}
# Save crop calendar clean data
write.csv(crop_calendar_clean, "clean_data/crop_calendar_clean.csv", row.names = FALSE)

# Save production clean data
write.csv(production_clean, "clean_data/production_clean.csv", row.names = FALSE)
```























